### ISSUE TITLE
Setup server

### ISSUE THREAD

**Issue by theunfriendly** [theunfriendly/musical-spoon#1]
1. django
2. open port

**Comment by theunfriendly** [comment]
Please install the django and python dependency @ghosthapper

**Comment by ghosthapper** [comment]
ok I will install the Django

**Comment by theunfriendly** [comment]
port 8000 open
Added firewall rule
firewall-cmd --zone=public --permanent --add-port=8000/tcp

**Comment by theunfriendly** [comment]
Port open 8000
django install
